# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0023_auto_20170322_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gmailid', models.UUIDField()),
                ('emailto', models.EmailField(max_length=254)),
                ('emailcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, size=None)),
                ('emailbcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, size=None)),
                ('subject', models.TextField(blank=True, default='')),
                ('salutation', models.TextField(blank=True, default='')),
                ('introduction', models.TextField(blank=True, default='')),
                ('valueproposition', models.TextField(blank=True, default='')),
                ('calltoaction', models.TextField(blank=True, default='')),
                ('signature', models.TextField(blank=True, default='')),
                ('introductionwordcount', models.IntegerField(blank=True)),
                ('valuepropositionwordcount', models.IntegerField(blank=True)),
                ('calltoactionwordcount', models.IntegerField(blank=True)),
                ('numberofopens', models.IntegerField(default=0)),
                ('isrepliedto', models.BooleanField(default=False)),
                ('nugget', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nugget', to='research.Nugget')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
                'ordering': ('created',),
            },
        ),
    ]
