# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20170322_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='calltoactionwordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='introductionwordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='valuepropositionwordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
