# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_email_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='selectedcalltoaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selectedcalltoaction', to='personas.CallToAction'),
        ),
        migrations.AlterField(
            model_name='email',
            name='selectednugget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selectednugget', to='research.Nugget'),
        ),
        migrations.AlterField(
            model_name='email',
            name='selectedvalueproposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selectedvalueproposition', to='personas.ValueProposition'),
        ),
    ]
