# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, default='', max_length=1000)),
                ('body', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'nuggets',
                'verbose_name': 'nugget',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=1000)),
                ('body', models.CharField(blank=True, default='', max_length=1000)),
                ('source', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'research pieces',
                'verbose_name': 'research piece',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('jobtitle', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'research',
                'verbose_name': 'research',
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='research.Research'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nugget', to='research.Piece'),
        ),
    ]
