# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
