# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20170306_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('clearbit', models.UUIDField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('crunchbase', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('logo', models.CharField(blank=True, default='', max_length=500)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'companies',
                'verbose_name': 'company',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('jobtitle', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
                ('companyname', models.CharField(blank=True, default='', max_length=200)),
                ('clearbit', models.UUIDField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='research.Company')),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'individuals',
                'verbose_name': 'individual',
            },
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ('created',), 'verbose_name': 'piece', 'verbose_name_plural': 'pieces'},
        ),
        migrations.RemoveField(
            model_name='research',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='research',
            name='company',
        ),
        migrations.RemoveField(
            model_name='research',
            name='email',
        ),
        migrations.RemoveField(
            model_name='research',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='research',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='research',
            name='lastname',
        ),
        migrations.AddField(
            model_name='research',
            name='individual',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='research', to='research.Individual'),
        ),
    ]
