# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20170308_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='other_data',
        ),
        migrations.AlterField(
            model_name='research',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='research.Individual'),
        ),
    ]
