# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20170309_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugget',
            name='speaker',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
