# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_nugget_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
