# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_individual_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='aggregator',
            field=models.TextField(blank=True, default=''),
        ),
    ]
