# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_individual_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'individual', 'verbose_name_plural': 'individuals'},
        ),
        migrations.AlterModelOptions(
            name='nugget',
            options={'verbose_name': 'nugget', 'verbose_name_plural': 'nuggets'},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'verbose_name': 'piece', 'verbose_name_plural': 'pieces'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'research', 'verbose_name_plural': 'research'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='created',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='created',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='nugget',
            name='created',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='created',
        ),
        migrations.RemoveField(
            model_name='research',
            name='created',
        ),
    ]
