# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_auto_20170313_1745'),
        ('research', '0011_piece_aggregator'),
    ]

    operations = [
    ]
