# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_auto_20170313_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuggetWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wrapper', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('quote', 'Quote'), ('testimonial', 'Testimonial'), ('hires', 'Hires'), ('promotes', 'Promotes'), ('leaves', 'Leaves'), ('retires', 'Retires'), ('acquires', 'Aquires'), ('merges_with', 'Merges With'), ('sells_assets_to', 'Sells Assets To'), ('expands_offices_to', 'Expands Offices To'), ('expands_offices_in', 'Expands Office In'), ('expands_facilities', 'Expands Facilities'), ('opens_new_location', 'Opens New Location'), ('increases_headcount_by', 'Increases Headcount By'), ('launches', 'Launches'), ('integrates_with', 'Integrates With'), ('is_developing', 'Is Developing'), ('receives_financing', 'Receives Financing'), ('invests_into', 'Invests Into'), ('goes_public', 'Goes Public'), ('closes_offices', 'Closes Offices'), ('decreases_headcount_by', 'Decreases Headcount By'), ('partners_with', 'Partners With'), ('receives_award', 'Receives Award'), ('recognized_as', 'Recognized As'), ('receives_award', 'Receives Award'), ('signs_new_client', 'Signs New Client'), ('files_suit_against', 'Files Suit Against'), ('has_issues_with', 'Has Issues With')], default='quote', max_length=100)),
                ('mergefields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'nugget wrappers',
                'verbose_name': 'nugget wrapper',
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='nugget',
            name='category',
            field=models.CharField(choices=[('quote', 'Quote'), ('testimonial', 'Testimonial'), ('hires', 'Hires'), ('promotes', 'Promotes'), ('leaves', 'Leaves'), ('retires', 'Retires'), ('acquires', 'Aquires'), ('merges_with', 'Merges With'), ('sells_assets_to', 'Sells Assets To'), ('expands_offices_to', 'Expands Offices To'), ('expands_offices_in', 'Expands Office In'), ('expands_facilities', 'Expands Facilities'), ('opens_new_location', 'Opens New Location'), ('increases_headcount_by', 'Increases Headcount By'), ('launches', 'Launches'), ('integrates_with', 'Integrates With'), ('is_developing', 'Is Developing'), ('receives_financing', 'Receives Financing'), ('invests_into', 'Invests Into'), ('goes_public', 'Goes Public'), ('closes_offices', 'Closes Offices'), ('decreases_headcount_by', 'Decreases Headcount By'), ('partners_with', 'Partners With'), ('receives_award', 'Receives Award'), ('recognized_as', 'Recognized As'), ('receives_award', 'Receives Award'), ('signs_new_client', 'Signs New Client'), ('files_suit_against', 'Files Suit Against'), ('has_issues_with', 'Has Issues With')], default='quote', max_length=100),
        ),
    ]
