# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20170313_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugget',
            name='additionaldata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
