# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_nugget_additionaldata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NuggetWrapper',
            new_name='NuggetTemplate',
        ),
        migrations.AlterModelOptions(
            name='nuggettemplate',
            options={'ordering': ('created',), 'verbose_name': 'nugget template', 'verbose_name_plural': 'nugget templates'},
        ),
        migrations.RenameField(
            model_name='nuggettemplate',
            old_name='wrapper',
            new_name='template',
        ),
    ]
