# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_auto_20170314_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuggettemplate',
            old_name='template',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='nuggettemplate',
            name='segue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nuggettemplate',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='category',
            field=models.CharField(choices=[('quote_from', 'Quote From'), ('quote_about', 'Quote By'), ('testimonial', 'Testimonial'), ('hires', 'Hires'), ('promotes', 'Promotes'), ('leaves', 'Leaves'), ('retires', 'Retires'), ('acquires', 'Aquires'), ('merges_with', 'Merges With'), ('sells_assets_to', 'Sells Assets To'), ('expands_offices_to', 'Expands Offices To'), ('expands_offices_in', 'Expands Office In'), ('expands_facilities', 'Expands Facilities'), ('opens_new_location', 'Opens New Location'), ('increases_headcount_by', 'Increases Headcount By'), ('launches', 'Launches'), ('integrates_with', 'Integrates With'), ('is_developing', 'Is Developing'), ('receives_financing', 'Receives Financing'), ('invests_into', 'Invests Into'), ('goes_public', 'Goes Public'), ('closes_offices', 'Closes Offices'), ('decreases_headcount_by', 'Decreases Headcount By'), ('partners_with', 'Partners With'), ('receives_award', 'Receives Award'), ('recognized_as', 'Recognized As'), ('receives_award', 'Receives Award'), ('signs_new_client', 'Signs New Client'), ('files_suit_against', 'Files Suit Against'), ('has_issues_with', 'Has Issues With')], default='quote', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuggettemplate',
            name='category',
            field=models.CharField(choices=[('quote_from', 'Quote From'), ('quote_about', 'Quote By'), ('testimonial', 'Testimonial'), ('hires', 'Hires'), ('promotes', 'Promotes'), ('leaves', 'Leaves'), ('retires', 'Retires'), ('acquires', 'Aquires'), ('merges_with', 'Merges With'), ('sells_assets_to', 'Sells Assets To'), ('expands_offices_to', 'Expands Offices To'), ('expands_offices_in', 'Expands Office In'), ('expands_facilities', 'Expands Facilities'), ('opens_new_location', 'Opens New Location'), ('increases_headcount_by', 'Increases Headcount By'), ('launches', 'Launches'), ('integrates_with', 'Integrates With'), ('is_developing', 'Is Developing'), ('receives_financing', 'Receives Financing'), ('invests_into', 'Invests Into'), ('goes_public', 'Goes Public'), ('closes_offices', 'Closes Offices'), ('decreases_headcount_by', 'Decreases Headcount By'), ('partners_with', 'Partners With'), ('receives_award', 'Receives Award'), ('recognized_as', 'Recognized As'), ('receives_award', 'Receives Award'), ('signs_new_client', 'Signs New Client'), ('files_suit_against', 'Files Suit Against'), ('has_issues_with', 'Has Issues With')], default='quote', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuggettemplate',
            name='mergefields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
