# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_merge_20170314_1921'),
        ('research', '0017_auto_20170314_2153'),
    ]

    operations = [
    ]
