# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_piece_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='publisheddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
