# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0023_auto_20170324_1749'),
        ('research', '0023_auto_20170324_1516'),
    ]

    operations = [
    ]
