# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0024_merge_20170324_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='group',
            field=models.CharField(choices=[('article', 'article'), ('testimonial', 'testimonial'), ('leadership', 'leadership'), ('aquisition', 'aquisition'), ('expansion', 'expansion'), ('new_offering', 'new_offering'), ('investment', 'investment'), ('cost_cutting', 'cost_cutting'), ('partnership', 'partnership'), ('recognition', 'recognition'), ('corporate_challenges', 'corporate_challenges'), ('job_position', 'job_position')], default='article', max_length=100),
        ),
    ]
