# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0025_auto_20170324_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
