# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0033_auto_20170411_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='group',
            field=models.CharField(choices=[('testimonial', 'testimonial'), ('partnership', 'partnership'), ('cost_cutting', 'cost_cutting'), ('leadership', 'leadership'), ('recognition', 'recognition'), ('investment', 'investment'), ('expansion', 'expansion'), ('job_position', 'job_position'), ('article', 'article'), ('new_offering', 'new_offering'), ('corporate_challenges', 'corporate_challenges'), ('aquisition', 'aquisition')], default='article', max_length=100),
        ),
    ]
