# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0034_auto_20170413_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='avatar',
            field=models.CharField(blank=True, default='https://s3.amazonaws.com/shakespeare-images/default_avatar.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='category',
            field=models.CharField(choices=[('acquires', 'Aquires'), ('administration', 'Administration'), ('business_analysis', 'Business Analysis'), ('chairmen', 'Chairmen'), ('closes_offices', 'Closes Offices'), ('data_analysis', 'Data Analysis'), ('decreases_headcount_by', 'Decreases Headcount By'), ('design', 'Design'), ('directors', 'Directors'), ('education', 'Education'), ('engineering', 'Engineering'), ('expands_facilities', 'Expands Facilities'), ('expands_offices_in', 'Expands Office In'), ('expands_offices_to', 'Expands Offices To'), ('files_suit_against', 'Files Suit Against'), ('finance', 'Finance'), ('general_technology', 'General Technology'), ('goes_public', 'Goes Public'), ('has_issues_with', 'Has Issues With'), ('health_care', 'Health Care'), ('hires', 'Hires'), ('hospitality', 'Hospitality'), ('human_resources', 'Human Resources'), ('increases_headcount_by', 'Increases Headcount By'), ('information_technology', 'Information Technology'), ('integrates_with', 'Integrates With'), ('invests_into', 'Invests Into'), ('invests_into_assets', 'Invests Into Assets'), ('is_developing', 'Is Developing'), ('launches', 'Launches'), ('leaves', 'Leaves'), ('maintenance', 'Maintenance'), ('management', 'Management'), ('marketing', 'Marketing'), ('merges_with', 'Merges With'), ('none', 'None'), ('opens_new_location', 'Opens New Location'), ('operations', 'Operations'), ('partners_with', 'Partners With'), ('partnerships', 'Partnerships'), ('promotes', 'Promotes'), ('publishing', 'Publishing'), ('purchasing', 'Purchasing'), ('quote_about', 'Quote About'), ('quote_from_company', 'Quote From Company'), ('quote_from_individual', 'Quote From Individual'), ('receives_award', 'Receives Award'), ('receives_financing', 'Receives Financing'), ('recognized_as', 'Recognized As'), ('retires', 'Retires'), ('sales', 'Sales'), ('sells_assets_to', 'Sells Assets To'), ('signs_new_client', 'Signs New Client'), ('software_development', 'Software Development'), ('support', 'Support'), ('testimonial', 'Testimonial'), ('transportation', 'Transportation')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuggettemplate',
            name='category',
            field=models.CharField(choices=[('acquires', 'Aquires'), ('administration', 'Administration'), ('business_analysis', 'Business Analysis'), ('chairmen', 'Chairmen'), ('closes_offices', 'Closes Offices'), ('data_analysis', 'Data Analysis'), ('decreases_headcount_by', 'Decreases Headcount By'), ('design', 'Design'), ('directors', 'Directors'), ('education', 'Education'), ('engineering', 'Engineering'), ('expands_facilities', 'Expands Facilities'), ('expands_offices_in', 'Expands Office In'), ('expands_offices_to', 'Expands Offices To'), ('files_suit_against', 'Files Suit Against'), ('finance', 'Finance'), ('general_technology', 'General Technology'), ('goes_public', 'Goes Public'), ('has_issues_with', 'Has Issues With'), ('health_care', 'Health Care'), ('hires', 'Hires'), ('hospitality', 'Hospitality'), ('human_resources', 'Human Resources'), ('increases_headcount_by', 'Increases Headcount By'), ('information_technology', 'Information Technology'), ('integrates_with', 'Integrates With'), ('invests_into', 'Invests Into'), ('invests_into_assets', 'Invests Into Assets'), ('is_developing', 'Is Developing'), ('launches', 'Launches'), ('leaves', 'Leaves'), ('maintenance', 'Maintenance'), ('management', 'Management'), ('marketing', 'Marketing'), ('merges_with', 'Merges With'), ('none', 'None'), ('opens_new_location', 'Opens New Location'), ('operations', 'Operations'), ('partners_with', 'Partners With'), ('partnerships', 'Partnerships'), ('promotes', 'Promotes'), ('publishing', 'Publishing'), ('purchasing', 'Purchasing'), ('quote_about', 'Quote About'), ('quote_from_company', 'Quote From Company'), ('quote_from_individual', 'Quote From Individual'), ('receives_award', 'Receives Award'), ('receives_financing', 'Receives Financing'), ('recognized_as', 'Recognized As'), ('retires', 'Retires'), ('sales', 'Sales'), ('sells_assets_to', 'Sells Assets To'), ('signs_new_client', 'Signs New Client'), ('software_development', 'Software Development'), ('support', 'Support'), ('testimonial', 'Testimonial'), ('transportation', 'Transportation')], default='quote', max_length=100),
        ),
        migrations.AlterField(
            model_name='piece',
            name='group',
            field=models.CharField(choices=[('article', 'article'), ('testimonial', 'testimonial'), ('leadership', 'leadership'), ('aquisition', 'aquisition'), ('expansion', 'expansion'), ('new_offering', 'new_offering'), ('investment', 'investment'), ('cost_cutting', 'cost_cutting'), ('partnership', 'partnership'), ('recognition', 'recognition'), ('corporate_challenges', 'corporate_challenges'), ('job_position', 'job_position')], default='article', max_length=100),
        ),
    ]
