# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0034_auto_20170413_1627'),
        ('research', '0023_auto_20170322_1710'),
    ]

    operations = [
    ]
