# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0035_auto_20170413_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
