# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0038_auto_20170415_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='group',
            field=models.CharField(choices=[('partnership', 'partnership'), ('testimonial', 'testimonial'), ('aquisition', 'aquisition'), ('investment', 'investment'), ('recognition', 'recognition'), ('cost_cutting', 'cost_cutting'), ('article', 'article'), ('expansion', 'expansion'), ('new_offering', 'new_offering'), ('corporate_challenges', 'corporate_challenges'), ('job_position', 'job_position'), ('leadership', 'leadership')], default='article', max_length=100),
        ),
    ]
