# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0039_auto_20170415_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='group',
            field=models.CharField(choices=[('recognition', 'recognition'), ('article', 'article'), ('new_offering', 'new_offering'), ('job_position', 'job_position'), ('cost_cutting', 'cost_cutting'), ('investment', 'investment'), ('aquisition', 'aquisition'), ('leadership', 'leadership'), ('corporate_challenges', 'corporate_challenges'), ('testimonial', 'testimonial'), ('expansion', 'expansion'), ('partnership', 'partnership')], default='article', max_length=100),
        ),
    ]
