# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0040_auto_20170415_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='group',
            field=models.CharField(choices=[('cost_cutting', 'cost_cutting'), ('new_offering', 'new_offering'), ('investment', 'investment'), ('testimonial', 'testimonial'), ('aquisition', 'aquisition'), ('article', 'article'), ('expansion', 'expansion'), ('leadership', 'leadership'), ('corporate_challenges', 'corporate_challenges'), ('job_position', 'job_position'), ('recognition', 'recognition'), ('partnership', 'partnership')], default='article', max_length=100),
        ),
    ]
