# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0041_auto_20170415_2029'),
        ('research', '0036_auto_20170413_1907'),
    ]

    operations = [
    ]
