# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0043_auto_20170501_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='clearbit',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
