# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0044_auto_20170501_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nugget',
            name='category',
            field=models.CharField(choices=[('acquires', 'Aquires'), ('business_analysis', 'Business Analysis'), ('data_analysis', 'Data Analysis'), ('directors', 'Directors'), ('engineering', 'Engineering'), ('expands_facilities', 'Expands Facilities'), ('expands_offices_in', 'Expands Office In'), ('expands_offices_to', 'Expands Offices To'), ('finance', 'Finance'), ('general_technology', 'General Technology'), ('goes_public', 'Goes Public'), ('hires', 'Hires'), ('human_resources', 'Human Resources'), ('increases_headcount_by', 'Increases Headcount By'), ('information_technology', 'Information Technology'), ('integrates_with', 'Integrates With'), ('invests_into', 'Invests Into'), ('is_developing', 'Is Developing'), ('launches', 'Launches'), ('leaves', 'Leaves'), ('management', 'Management'), ('marketing', 'Marketing'), ('merges_with', 'Merges With'), ('none', 'None'), ('opens_new_location', 'Opens New Location'), ('operations', 'Operations'), ('partners_with', 'Partners With'), ('partnerships', 'Partnerships'), ('promotes', 'Promotes'), ('quote_about', 'Quote About'), ('quote_from_company', 'Quote From Company'), ('quote_from_individual', 'Quote From Individual'), ('receives_award', 'Receives Award'), ('receives_financing', 'Receives Financing'), ('recognized_as', 'Recognized As'), ('sales', 'Sales'), ('signs_new_client', 'Signs New Client'), ('software_development', 'Software Development'), ('support', 'Support'), ('testimonial', 'Testimonial')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuggettemplate',
            name='category',
            field=models.CharField(choices=[('acquires', 'Aquires'), ('business_analysis', 'Business Analysis'), ('data_analysis', 'Data Analysis'), ('directors', 'Directors'), ('engineering', 'Engineering'), ('expands_facilities', 'Expands Facilities'), ('expands_offices_in', 'Expands Office In'), ('expands_offices_to', 'Expands Offices To'), ('finance', 'Finance'), ('general_technology', 'General Technology'), ('goes_public', 'Goes Public'), ('hires', 'Hires'), ('human_resources', 'Human Resources'), ('increases_headcount_by', 'Increases Headcount By'), ('information_technology', 'Information Technology'), ('integrates_with', 'Integrates With'), ('invests_into', 'Invests Into'), ('is_developing', 'Is Developing'), ('launches', 'Launches'), ('leaves', 'Leaves'), ('management', 'Management'), ('marketing', 'Marketing'), ('merges_with', 'Merges With'), ('none', 'None'), ('opens_new_location', 'Opens New Location'), ('operations', 'Operations'), ('partners_with', 'Partners With'), ('partnerships', 'Partnerships'), ('promotes', 'Promotes'), ('quote_about', 'Quote About'), ('quote_from_company', 'Quote From Company'), ('quote_from_individual', 'Quote From Individual'), ('receives_award', 'Receives Award'), ('receives_financing', 'Receives Financing'), ('recognized_as', 'Recognized As'), ('sales', 'Sales'), ('signs_new_client', 'Signs New Client'), ('software_development', 'Software Development'), ('support', 'Support'), ('testimonial', 'Testimonial')], default='quote', max_length=100),
        ),
    ]
