# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_model_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('organizations.organizationuser',),
        ),
    ]
