# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_calltoaction_valueproposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='valueproposition',
            name='persona',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='personas',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='valueproposition',
            name='personas',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
    ]
