# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20170224_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='personas',
            field=models.ManyToManyField(related_name='call_to_action_personas', to='personas.Persona'),
        ),
        migrations.AlterField(
            model_name='valueproposition',
            name='personas',
            field=models.ManyToManyField(related_name='value_proposition_personas', to='personas.Persona'),
        ),
    ]
