# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20170224_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueproposition',
            name='body',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
