# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20170301_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name': 'call to action', 'verbose_name_plural': 'calls to action'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterModelOptions(
            name='valueproposition',
            options={'verbose_name': 'value proposition', 'verbose_name_plural': 'value propositions'},
        ),
        migrations.RemoveField(
            model_name='calltoaction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='created',
        ),
        migrations.RemoveField(
            model_name='valueproposition',
            name='created',
        ),
    ]
