# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20170313_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'ordering': ('created',), 'verbose_name': 'call to action', 'verbose_name_plural': 'calls to action'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('created',), 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterModelOptions(
            name='valueproposition',
            options={'ordering': ('created',), 'verbose_name': 'value proposition', 'verbose_name_plural': 'value propositions'},
        ),
    ]
