# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_auto_20170313_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='valueproposition',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
