# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_auto_20170405_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='valueproposition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='valueproposition',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
