# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0011_auto_20170420_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='personas',
        ),
        migrations.RemoveField(
            model_name='valueproposition',
            name='personas',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calltoactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valueproposition',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valueprops', to=settings.AUTH_USER_MODEL),
        ),
    ]
